### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by juhaaa** [JVS23/TsoHa-Forum#1]
Sovellus aukesi ohjeiden mukaan toimien ja luvatut tämänhetkiset toiminnot myös toimivat. Pystyin luomaan itselleni käyttäjätilin ja postaamaan foorumille. Sovelluksen ulkoasu vaikuttaa lupaavalta. Omaa silmää miellyttää tälläinen selkeä ja  pelkistetty tyyli. 

![Screenshot from 2023-02-08 18-42-27](https://user-images.githubusercontent.com/2658841/217594913-8d032c23-344e-4509-92b4-30ead1c24d76.png)

Ulkoasu ja elementtien sijoittelu vaikuttaa muutenkin harkitulta. Painikkeet on sijoiteltu intuitiivisesti ja käytön mahdollistavat toiminnallisuudet ovat helposti löydettävissä. 
Tällä hetkellä  kaikki uudet  "säikeet" ilmestyvät ilmeisesti samaan jonoon. Jos niitä on tuhansia, ja oletetaan ettei aiheena olisi pelkät kissat, voisi mahdollisuus jakaa niitä aihealueittain olla kannatettavaa. Toki voihan kissoistakin olla eri aiheisia kuvia. Tämä kuitenkin mahdollistaisi kuvien mukavamman selaamisen. Ja ehkä voisi auttaa puuttuvien tietokantataulujen kehittämisessä. Nyt jälkikäteen huomasin, että tämä onkin todo- listalla. 

Toinen ominaisuus mitä käyttäjänä toivoisi, olisi mahdollisuus poistaa oma tuotoksensa, jos alkaa kaduttaa.

Koodia on vielä tällä hetkellä maltillinen määrä, mutta projektin kasvaessa voisi olla hyvä esimerkiksi eriyttää sql- käskyt omaan tiedostoonsa ja tuoda sieltä tarvittaessa käyttöön. Tämä mahdollistaa mielestäni koodin selkiyttämisen, kun joissain tapauksissa pitkät sql kyselyt ovat poissa näkyvistä.

Tietokannan rakenteessa voisi mahdollisesti harkita TEXT tietotyypin muuttamista VARCHAR(n) tietotyyppiin. Tällä hetkellä on mahdollista luoda esimerkiksi mahdottoman pitkiä käyttäjänimiä. Voiko tämä olla haitaksi muissakin kohdissa ja sotkea layoutin? Toki tämä pitäisi sovelluksessa muutenkin tarkistaa, joten riittänee lisätä ehto sinne. 

![Screenshot from 2023-02-08 19-16-10](https://user-images.githubusercontent.com/2658841/217604119-bddecfe1-83b0-4878-a569-1ed97801a1c1.png)

**Comment by JVS23** [comment]
Kiitoksia erinomaisesta vertaisarviosta sekä kehuista, otan hyvin todennäköisesti kaikki ehdotuksesi käytäntöön! Propsit myös tyylikkäästä koirakuvasta. :thumbsup:
