### ISSUE TITLE
2. Vertaisarviointi

### ISSUE THREAD

**Issue by JuhoPaananen** [JVS23/TsoHa-Forum#2]
## Koodikatselmointi:

- Koodi oli mielestäni siistiä, mutta harkitsisin modulaarisempaa rakennetta. Nyt routes.py moduuli vastasi lähes kaikista ohjelman toiminnallisuuksista.
  - Tietokantatoiminnot voisi sijoittaa omaan moduuliin
  - Reititys itsessään omassa moduulisssa "routes"
  - Käyttäjä- ja istuntohallinta omassaan
  - Tietokantayhteydet omassaa jne.
- Koodissa oli tarkistuksia käyttäjän syötteille, hyvä! Myös JavaScript tarkistuksia löytyy käyttäjän ohjeistamiseksi.
- Ulkoasun toteutus oli hyvällä tasolla, tykkäsin tyylistä.
- Toteutetut tietokantatoiminnot olivat hyviä. SQL-komentoja voisi pilkkoa osiin luettavuuden helpottamiseksi.
- Mielestäni COMMIT-viestit olivat pääosin ytimekkäitä ja informatiivisia.

## Sovellustestaus:

- Sain ohjelman käynnistymään paikallisesti verrattain helposti ohjeita seuraamalla
- Sain tietokannan toimimaan hyvin paikallisesti schema-sql tiedostosta.
- Sovellus toimi omasta mielestäni kiitettävästi README.md-tiedoston toteutettujen toiminnallisuuksien puolesta. Hyvä.
- Käyttäjäkokemusta parannettu flash-viesteillä. 
- Tässä vaiheessa kurssia, voisi olla hieman laajemmin toteutettu sovelluksen toiminnallisuuksia.

**Hyvää työtä ja tsemppiä loppupalautukseen!**

**Comment by JVS23** [comment]
Kiitoksia erinomaisesta palautteesta, hyviä vinkkejä!
